---
- name: Set resolv_conf_file if running in container
  ansible.builtin.set_fact:
    resolv_conf_resolv_conf_file: "{{ resolv_conf_resolv_conf_file }}.docker"
  when:
    - ansible_virtualization_type | regex_search("docker|podman|container")


- name: Deploy {{ resolv_conf_resolv_conf_file }}
  ansible.builtin.template:
    src: templates/resolv_conf.j2
    dest: "{{ resolv_conf_resolv_conf_file }}"
    mode: "0644"


...
