---
base_packages_package_set:
  - bc
  - bind-utils
  - bzip2
  - cronie
  - deltarpm
  - file
  - ftp
  - git
  - htop
  - iperf
  - iptraf
  - jwhois
  - lsof
  - man
  - mlocate
  - net-snmp
  - net-tools
  - nfs-utils
  - ntp
  - rsync
  - screen
  - sudo
  - tar
  - tcpdump
  - telnet
  - traceroute
  - tree
  - unzip
  - vim-enhanced
  - vnstat
  - wget
  - yum-utils
  - zip


...
