---
- name: Set hostname for host
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  notify:
    - "Restart_syslog_{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}"


...
