---
kind: pipeline
type: docker
name: CentOS_9-Ansible-Pipeline

trigger:
  branch:
    exclude:
      - main
  event: [push]

steps:
  - name: ansible_environment_verify
    image: gitea.thezengarden.net/podman/ansible-dev/centos9:release
    commands:
      - . ./.drone.env
      - env
      - git log -1
      - ansible --version
      - ansible-lint --version

  - name: ansible_lint
    image: gitea.thezengarden.net/podman/ansible-dev/centos9:release
    commands:
      - . ./.drone.env
      - ansible-lint --offline --nocolor $ANSIBLE_LINT_EXCLUSION


---
kind: pipeline
type: docker
name: Fedora_39-Ansible-Pipeline

trigger:
  branch:
    exclude:
      - main
  event: [push]

steps:
  - name: ansible_environment_verify
    image: gitea.thezengarden.net/podman/ansible-dev/fedora39:release
    commands:
      - . ./.drone.env
      - env
      - git log -1
      - ansible --version
      - ansible-lint --version

  - name: ansible_lint
    image: gitea.thezengarden.net/podman/ansible-dev/fedora39:release
    commands:
      - . ./.drone.env
      - ansible-lint --offline --nocolor $ANSIBLE_LINT_EXCLUSION


---
kind: pipeline
type: docker
name: Debian_11-Ansible-Pipeline

trigger:
  branch:
    exclude:
      - main
  event: [push]

steps:
  - name: ansible_environment_verify
    image: gitea.thezengarden.net/podman/ansible-dev/debian11:release
    commands:
      - . ./.drone.env
      - env
      - git log -1
      - ansible --version
      - ansible-lint --version

  - name: ansible_lint
    image: gitea.thezengarden.net/podman/ansible-dev/debian11:release
    commands:
      - . ./.drone.env
      - ansible-lint --offline --nocolor $ANSIBLE_LINT_EXCLUSION


---
kind: pipeline
type: docker
name: Debian_12-Ansible-Pipeline


trigger:
  branch:
    exclude:
      - main
  event: [push]

steps:
  - name: ansible_environment_verify
    image: gitea.thezengarden.net/podman/ansible-dev/debian12:release
    commands:
      - . ./.drone.env
      - env
      - git log -1
      - ansible --version
      - ansible-lint --version

  - name: ansible_lint
    image: gitea.thezengarden.net/podman/ansible-dev/debian12:release
    commands:
      - . ./.drone.env
      - ansible-lint --offline --nocolor $ANSIBLE_LINT_EXCLUSION
