---
- name: Set host IP address or set a default
  ansible.builtin.set_fact:
    host_ip : "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"


- name: Install Perl if needed
  ansible.builtin.package:
    name  : perl
    state : present


- name: Get system uptime from script
  ansible.builtin.script:
    cmd        : "scripts/get_uptime.pl {{ ansible_uptime_seconds }}"
  register     : node_uptime
  changed_when : false


- name: Update MOTD
  ansible.builtin.template:
    src        : templates/motd.j2
    dest       : "{{ motd_motd_file }}"
    mode       : "0644"
  changed_when : false


...

