---
- name: Include distribution specific variables or include defaults
  block:
    - name: Include distribution specific variables
      ansible.builtin.include_vars:
        file: "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"


  rescue:
    - name: Non-supported distribution; using default package set
      ansible.builtin.include_vars:
        file: default_packages.yml


- name: Install EPEL for CentOS hosts - Required for some packages
  ansible.builtin.package:
    name  : epel-release
    state : present
  when:
    - ansible_distribution | lower == 'centos'


- name: Install package set
  ansible.builtin.package:
    name  : "{{ base_packages_package_set }}"
    state : present


...
